version: '3.9'

services:
  web:
    build: .
    container_name: web_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: db_service
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
    name: db_data_volume